name: Authentication Tweaks
description: Adds useful authentication features.
type: Drupal CMS
install:
  - bpmn_io
  - drupal_cms_helper
  - eca_base
  - eca_form
  - eca_misc
  - eca_user
  - eca_ui
  - login_emailusername
  - modeler_api
  - token
config:
  # If the active config doesn't match what's in the recipe, we can assume that the site
  # owner has made their own tweaks to the authentication flows, and we respect those.
  strict: false
  actions:
    system.site:
      simpleConfigUpdate:
        page.403: '/user/login'
    user.settings:
      simpleConfigUpdate:
        register: admin_only
